{
 "title": "IIoT Edge Telemetry Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iiot_telemetry\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"esp32_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iiot_telemetry\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"esp32_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"temperature\")"
    }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"iiot_telemetry\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"esp32_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")"
    }
   ]
  },
  {
   "title": "Pressure (hPa)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"iiot_telemetry\")\r\n  |> range(start: -15m)\r\n  |> filter(fn: (r) => r._measurement == \"esp32_telemetry\")\r\n  |> filter(fn: (r) => r._field == \"pressure\")"
    }
   ]
  }
 ]
}