[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_port = COM9
monitor_port = COM9

lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit Unified Sensor
    emelianov/modbus-esp8266
    bblanchon/ArduinoJson
    knolleary/PubSubClient